version: '3.7'
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    networks:
      - chmura_int
  client:
    build:
      context: ./client
    ports:
      - "5000:5000"
    networks:
      - chmura_int
networks:
  chmura_int:
    internal: true
